---
title: "Welcome"
---

## Introduction

Current trends among industries ranging from Insurance to Manufacturing (as well as many other professions) are pushing the need for data literacy. *This Course - Data Wrangling and Visualization* provides learners with the technical skills needed to competently work with and visualize data. More specifically this course will allow learners to use data-driven programming in Python for the handling, formatting, and visualization of messy and complex data. Learners will implement data wrangling techniques and the grammar of graphics process in visualizing complex data.

# Who is served by this course?

Learners that are driven by curiosity and interested in how decisions are made will be attracted to this course (sometimes called data intuition). Those that have a more empathetic approach to how the world works, people think, and how problems are solved will also have interest. Finally, those that have an eye for visualization and how information is communicated will be benefit from this course.

The primary difference in the type of course participants will be between those that are completing a data science (or statistics) degree and those that are from other degrees on campus but see the need for data interpretation and programming. This course will support students that know they need these analytical/programming capabilities in their respective areas of study and/or employment. With the strong demand for employees with programming and analytics capability across the US and world this class will give participants a significant advantage over others in their respective domains.

## Course Mission Statement

Use data-driven programming in Python for the handling, formatting, and visualization of messy and complex data. Students will implement data wrangling techniques and the [grammar of graphics](http://vita.had.co.nz/papers/layered-grammar.html){target="blank"} process in visualizing complex data.

## Course Outcomes

At the completion of this course, successful students will be able to:

1.  Convert data from varied formats or structures to a [tidy format](http://vita.had.co.nz/papers/tidy-data.html){target="blank"} for analysis and visualization.
2.  Clean, transform, and merge data attributes/variables appropriately.
3.  Effectively display and communicate meaning from spatial, temporal, and textual data.
4.  Articulate the process, benefits, and challenges of big data manipulation.
5.  Use current analysis, presentation, and collaboration tools in the data science field (E.g. Python, GitHub, Slack, etc).

------------------------------------------------------------------------