---
title: "task-17"
---

## Task 17: My investment is better than yours

### Background

The stock market is overflowing with data. There are many python libraries that allow us to get quick access to information on publicly traded companies. Imagine that you and a friend each purchased about \$1,000 of stock in three different stocks at the start of October last year, and you want to compare your performance up to this week. Use the stock shares purchased and share prices to demonstrate how each of you fared over the period you were competing (assuming that you did not change your allocations).

-   [Course Website](../index.html)

```{=html}
<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>
```

### Reading

This reading will help you complete the tasks below.

-   o [Yfinance Tickers API](https://ranaroussi.github.io/yfinance/reference/api/yfinance.Tickers.html#yfinance.Tickers){target="blank"}

### Tasks

-   [ ] Take notes on your reading of the new libraries in your marimo notebook.
-   [ ] List the three stocks that your friend picks and the three that you pick
-   [ ] Pull the price performance data using the `yfinance` library
-   [ ] Build a visualization that shows who is winning each day of the competition
-   [ ] In the previous visualization or with another visualization show which stock is helping the winner of the competition
-   [ ] Create a marimo notebook with 1-2 paragraphs summarizing your graphics and the choices you made in the data presentation
-   [ ] Export your notebook to `.html` abd have both the notebook and HTML into your git repository