---
title: "task-11"
---

## Task 11: Strings and Regex

### Background

Using Regular Expressions (Regex) and String Processing Functions to find character string patterns is a valuable tool in data analysis and is available with all operating systems and many different programming languages. It is a powerful tool once it is understood. The `str` namespace in Polars gives you access to String Precessing Functions that you can combine with Regex to write performant string queries. The three tasks below can be completed in many different ways. As a challenge, my code to complete this entire task less than 10 lines.

-   [Back](javascript:window.history.back();) or [Course Website](https://quickskilling.github.io/visualization_and_wrangling_development/)

```{=html}
<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>
```

### Reading

This reading will help you complete the tasks below.

-   o [Python for Data Science - Strings and Text](https://python4ds.com/strings.html){target="blank"}
-   o [Polars - Strings](https://docs.pola.rs/user-guide/expressions/strings/)
-   o [Regular Expression examples (optional)](https://qntm.org/files/re/re.html){target="blank"}
-   o [Regular Expression support applet (optional)](https://regex101.com/){target="blank"}

### Tasks

-   [ ] Use the `pl.read_lines()` function to read in each string - [randomletters.txt](https://byuistats.github.io/M335/data/randomletters.txt){target="blank"} and [randomletters_wnumbers.txt](https://byuistats.github.io/M335/data/randomletters_wnumbers.txt){target="blank"}
-   [ ] With the `randomletters.txt` file, pull out every 1700 letter (e.g. 1, 1700, 3400, …) and find the quote that is hidden - the quote ends with a period
-   [ ] With the `randomletters_wnumbers.txt` file, find all the numbers hidden and convert those numbers to letters using the letters order in the alphabet to decipher the message
-   [ ] With the `randomletters.txt` file, remove all the spaces and periods from the string then find the longest sequence of vowels.
-   [ ] Save your notebook to your repository and be ready to share your code solution in our weekly meeting