---
title: "task-09"
---

## Task 9: Same Data Different Format

### Background

Data formats are varied and differ by domains and software. We could spend weeks on the different formats and file types that companies and governments use to store their data. We will practice with a few standard formats that are often used for storing data. In the future, you will most likely have to do some research to figure out other formats. We have a challenge to read in the five formats of the [DOW data](https://github.com/byuistats/data/tree/master/Dart_Expert_Dow_6month_anova){target="blank"} and checking that they are all identical using `assert_frame_equal()` from `polars.testing`. One final note, your Python script should do all the work. That is your script should download the files and/or read directly from the web location of the file.

-   [Back](javascript:window.history.back();) or [Course Website](https://quickskilling.github.io/visualization_and_wrangling_development/)

```{=html}
<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>
```

### Reading

This reading will help you complete the tasks below.

-   o [Python for Data Science - Data Import](https://python4ds.com/exploratory-data-analysis.html){target="blank"}

### Tasks

-   [ ] Take notes on your reading of the specified 'Python for Data Science' chapter in in a marimo notebook.
-   [ ] Use the appropriate functions to read in the five files found on [GitHub](https://github.com/byuistats/data/tree/master/Dart_Expert_Dow_6month_anova){target="blank"}
-   [ ] Check that all five files you have imported into R are in fact the same with `assert_frame_equal()`
-   [ ] Use one of the files to make a graphic showing the performance of the Dart, DJIA, and Pro stock selections
    -   [ ] Include a boxplot, the jittered returns, and the average return in your graphic
-   [ ] Create a marimo notebook with your code and graphics
-   [ ] Export your notebook to `.html` and have both the notebook and HTML into your git repository
-   [ ] Schedule a mid-semester 15-minute interview with a mentor to discuss your progress.