---
title: "task-08"
---

## Task 8: World Data Investigations - Part 2

### Background

The [Our World in Data](https://ourworldindata.org/){target="blank"} website has world data. It is nice that they have provided graphics and then the data that they used to generate the graphics. Once again, we are going to build visualizations in R using their data.

-   [Course Website](../index.html)

```{=html}
<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>
```

### Reading

This reading will help you complete the tasks below.

-   o [Chapter 7: R for Data Science - Exploratory Data Analysis](http://r4ds.had.co.nz/exploratory-data-analysis.html){target="blank"}
-   o [devtoools R Package](https://github.com/hadley/devtools){target="blank"}

### Tasks

-   [ ] Take notes on your reading of the specified 'R for Data Science' chapter in the README.md or in a '.R' script in the class task folder
-   [ ] Explore the world data on `financing_healthcare` and create an interesting graphic that highlights this dataset in relation to child mortality.
    -   [ ] Use `devtools::install_github("drsimonj/ourworldindata")` to get a larger dataset on `financing_healthcare`
    -   [ ] Create a graphic that you could use in a final presentation to summarize world child mortality (`child_mort` column)
-   [ ] Push your `.Rmd`, `.md`, and `.html` to your GitHub repo