---
title: "task-07"
---

## Task 7: Data to Answer Questions

### Background

Finding good data takes time, and can take longer than the time to tidy your data. This task could easily take 3-6 hours to find the data you need for your final project. After you find good data sources make sure to complete the remaining tasks.

-   [Back](javascript:window.history.back();) or [Course Website](https://quickskilling.github.io/visualization_and_wrangling_development/)

```{=html}
<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>
```

### Reading

This reading will help you complete the tasks below.

-   o [Finding data to answer your question](https://www.dataquest.io/blog/free-datasets-for-projects/){target="blank"}
-   o [Find a post from the functional art](http://www.thefunctionalart.com){target="blank"}
-   o [Polars DataFrames and Series](https://docs.pola.rs/user-guide/concepts/data-types-and-structures/){target="blank"}
-   o [Polars Lists and Arrays](https://docs.pola.rs/user-guide/expressions/lists-and-arrays/){target="blank"}

### Tasks

-   [ ] Take notes on your reading of Polars in a marimo notebook.
-   [ ] Review the "What do people do with new" data link above and write one quote that resonated with you in your notebook.
-   [ ] Build an interactive document that has links to sources with a description of the quality of each
    -   [ ] Find 3-5 potential data sources (that are free) and document some information about the source
    -   [ ] Add cells in your notebook that reads in, formats, and visualizes the data using the principles of exploratory analysis
    -   [ ] Write a short summary of the read in process and some coding secrets you learned
    -   [ ] Include 2-3 quick visualizations that you used to check the quality of your data
    -   [ ] Summarize the limitations of your final compiled data in addressing your original question
-   [ ] After formatting your data identify any follow on or alternate questions that you could use for your project