---
title: "task-13"
---

## Task 13: Controlling categorical variables (factors)

### Background

When we are visualizing data with categorical variables, we have to deal with character strings as groupings. The problem with summarizing categorical data in a table or a plot is how to order the groups. Using the concept of Factors allows us to dictate the order of these groupings for presentation. We will revisit the [stock data](https://github.com/byuistats/data/tree/master/Dart_Expert_Dow_6month_anova){target="blank"} from a previous task to create a table and a plot that has the months correctly labeled and ordered.

-   [Course Website](../index.html)

```{=html}
<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>
```

### Reading

This reading will help you complete the tasks below.

-   o [Chapter 15: Python for Data Science - Factors](https://byuidatascience.github.io/python4ds/factors.html){target="blank"}

### Tasks

-   [ ] Take notes on your reading of the specified 'Python for Data Science' chapter in in a marimo notebook.
-   [ ] Load your "tidy" data from task 10 using the stock return data
-   [ ] Create a plot that shows the six-month returns by the month in which the returns are collected using the eight years of data
-   [ ] Include your plots in a marimo notebook with short paragraphs describing your plots.
-   [ ] Export your notebook to `.html` and have both the notebook and HTML into your git repository