---
title: "task-05"
---

## Task 5: World Data Investigation

### Background

The [Our World in Data](https://ourworldindata.org/){target="blank"} website has world data. It is nice that they have provided graphics and then the data that they used to generate the graphics. We are going to recreate some of their visualizations in Python and then make them better.

-   [Back](javascript:window.history.back();) or [Course Website](https://quickskilling.github.io/visualization_and_wrangling_development/)

```{=html}
<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>
```

### Reading

This reading will help you complete the tasks below.

-   o [Chapter 28: Python for Data Science - Graphics for communication](https://byuidatascience.github.io/python4ds/graphics-for-communication.html){target="blank"}
-   o [Chapter 6: Python for Data Science - Scripts](https://byuidatascience.github.io/python4ds/workflow-scripts.html){target="blank"}
-   o [Chapter 11: Python for Data Science - Data Import](https://byuidatascience.github.io/python4ds/data-import.html){target="blank"}

### Tasks

-   [ ] Take notes on your reading of the specified 'Python for Data Science' chapter in a marimo notebook.
-   [ ] Review the [Our World in Data](https://ourworldindata.org/){target="blank"} webpage and find a graphic that interests you.
    -   [ ] Recreate that graphic in R after downloading the data from their website
-   [ ] Explore the world data on `child_mortality` and create an interesting graphic that highlights this dataset.
    -   [ ] Use `owid-catalog` to get a larger dataset on `child_mortality`. This will require `uv add owid-catalog.`
    -   [ ] Create a graphic that you could use in a presentation to summarize world child mortality
-   [ ] Create a marimo notebook with for your plots with short paragraph describing those plots
-   [ ] Export your notebook to `.html` and have both the notebook and HTML into your git repository