---
title: "task-06"
---

## Task 6: Developing a graphic

### Background

Before we can start to answer business questions we need to become familiar with our data. Often, you will want to start with the [data dictionary](https://www.bridging-the-gap.com/data-dictionary/). However, you can also just dive into the data and gain understanding based on the variable names and types.

Beyond the variable descriptions is how the variables relate to each other. We can create tables or visualizations that summarize how different variables relate to each other. At this point we are deepening our understanding as well as beginning our analysis.

**Remember: Your job is to become the data expert not the domain expert.** You will build domain skills but you are not going to replace domain experts. People will depend on you to have a firm understanding of what data your company has available to answer domain specific questions.

Use `nycflights13 -> flights # uv add nycflights13` to practice your data summary and data investigation through visualization skills.

-   [Back](javascript:window.history.back();) or [Course Website](https://quickskilling.github.io/visualization_and_wrangling_development/)

```{=html}
<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>
```

### Reading

This reading will help you complete the tasks below.

-   o [Python for Data Science - Graphics for communication](https://python4ds.com/communicate-plots.html){target="blank"}

### Tasks

-   [ ] Find an insightfull relationship between two of the variables (columns) and display that relationship in a table or graphic
    -   [ ] Provide a distributional summary of the relevant variable in `nycflights13 -> flights`
    -   [ ] Build bivariate summaries of the relevant variables
    -   [ ] Document the iterative script that built to your insightful relationship
-   [ ] Create a marimo notebook that has your data visualization development with 1-2 paragraphs summarizing your 2 finalized graphics and the choices you made in the data presentation
-   [ ] Save your `.png` images of each your final graphics and push all your work to your repository.