---
title: "task-18"
---

## Task 18: The US Grocer (KR)

### Background

Interactive visualizations can often be powerful for data investigations. They let your team get at questions in real time. Use the Kroger (KR) stock price to build an interactive visualization of their performance over the last five years. Take some time to build a couple of different visualizations that show Krogers performance. See the task items below for a description.

-   [Back](javascript:window.history.back();) or [Course Website](https://quickskilling.github.io/visualization_and_wrangling_development/)

```{=html}
<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>
```

### Reading

This reading will help you complete the tasks below.

-   o [The Dygraphs Blog](http://blog.dygraphs.com/2014/09/pydygraphs-dygraphs-plotting-module-for.html){target="blank"}
-   o [Yfinance Tickers API](https://ranaroussi.github.io/yfinance/reference/api/yfinance.Tickers.html#yfinance.Tickers){target="blank"}

### Tasks

-   [ ] Take notes on your reading of the new libraries in your marimo notebook.
-   [ ] Build the `pydygraphs` plot that shows the Kroger (KR) stock price performance over 5 years.
-   [ ] Imagine that you invested \$10,000 in kroger about two years ago on April 5th. Make a graph with Pydygraphs that shows performance `dyRebased()` to \$10,000.
-   [ ] Annotate the graphic with a note of the reason at two or more time points, or intervals, where the price had significant shifts.
-   [ ] Create a marimo notebook with 1-2 paragraphs summarizing your graphics and the choices you made in the data presentation
-   [ ] Export your notebook to `.html` abd have both the notebook and HTML into your git repository