---
title: "cs-01"
---

## Case Study 1: Critiquing Visualizations

### Background

Your first weekly project requires you to **submit** a review of 4-5 different data visualizations used to answer specific questions. Some fun websites are [pudding.cool](https://pudding.cool/){target="blank"}, [ourworldindata](https://ourworldindata.org/){target="blank"}, and [priceonomics](https://priceonomics.com/){target="blank"} (but you can use any website, blog, or article with a good visualization).

-   [Course Website](.../index.html)

### Tasks

```{=html}
<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>
```

-   [ ] Find 4-5 examples of data-driven answers and write a one-paragraph review of each.
    -   [ ] List 2-3 items that are unique/good
    -   [ ] Identify 1 issue with each example
-   [ ] Create a marimo notebook
    -   [ ] Title it Case Study 1
    -   [ ] Include links or embedded images to the visualization post you found in the markdown
    -   [ ] Write a one paragraph critique of each visualization
    -   [ ] Export your notebook to `.html` and have both the notebook and HTML into your git repository