---
title: "cs-04"
---

## Case Study 4: Reducing Gun Deaths (FiveThirtyEight)

### Background

The world is a dangerous place. During 2015 and 2016 there was a lot of discussion in the [news about police shootings](http://www.cbsnews.com/pictures/controversial-police-shootings/){target="blank"}. [FiveThirtyEight](https://fivethirtyeight.com/){target="blank"} reported on [gun deaths in 2016](https://fivethirtyeight.com/features/gun-deaths/){target="blank"}. As leaders in data journalism, they have posted a clean version of this data in their GitHub repo called [full_data.csv](https://github.com/fivethirtyeight/guns-data){target="blank"} for us to use.

While their visualizations focused on yearly averages, our client wants to create commercials that help reduce the gun deaths in the US. They would like to target the commercials in different seasons of the year (think month variable) to audiences that could have the most impact in reducing gun deaths. Our challenge is to summarize and visualize seasonal trends across the other variables in these data.

-   [Course Website](.../index.html)

### Tasks

```{=html}
<style>
ul {
   color: black;
   list-style-type: none;
   list-style-position: outside;

}

</style>
```

-   [ ] Provide a brief summary of the [FiveThirtyEight article](https://fivethirtyeight.com/features/gun-deaths/){target="blank"}
    -   [ ] Create one plot that provides similar insight to their visualization in the article. It does not have to look like theirs.
    -   [ ] Write a short paragraph summarizing their article
-   [ ] Address the client's need for emphasis areas of their commercials for different seasons of the year.
    -   [ ] Provide plots that help them know the different potential groups (variables) they could address in different seasons (2-4 visualizations seem necessary)
    -   [ ] Write a short paragraph describing each image
-   [ ] Export your notebook to `.html` and have both the notebook and HTML into your git repository
-   [ ] Find two other student's compiled files in their repository and provide feedback using the issues feature in GitHub (If they already have three issues find a different student to critique)
-   [ ] Address 1-2 of the issues posted on your project and push the updates to GitHub